---
- name: Download alertmanager
  unarchive:
    src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy alertmanager executable to bin
  copy:
    dest: "/usr/local/bin/alertmanager"
    src: "/tmp/alertmanager"
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
    remote_src: yes
    mode: 0755

- name: Delete alertmanager archieve
  file:
    path: '/tmp/alertmanager-{{ version }}.linux-amd64'
    state: absent

- name: Create alertmanager data directory
  file:
    path: "/data/alertmanager/"
    state: directory
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
    mode: 0755

- name: Create alertmanager config directory
  file:
    path: "/etc/alertmanager/"
    state: directory
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
    mode: 0755

- name: Copy alertmanager config
  copy:
    dest: "/etc/alertmanager/alertmanager.yaml"
    src: "{{ role_path }}/conf/alertmanager.yaml"

- name: Setup alertmanager-0
  include_tasks: "alertmanager-0.yaml"
  when: inventory_hostname == groups.alertmanager[0]

- name: Setup alertmanager-1
  include_tasks: "alertmanager-1.yaml"
  when: inventory_hostname == groups.alertmanager[1]